export type FieldType = 'text'|'phone'|'email'|'number'|'currency'|'date'|'time'|'select'|'multiline'|'file'|'image'|'signature'|'location';
export type FormField = { name:string; label:string; type:FieldType; required?:boolean; options?:string[] };
export type FormSchema = { formId:string; sections:{ title:string; fields:FormField[] }[] };

const f=(name:string,label:string,type:FieldType='text',required=false,options?:string[]):FormField=>({name,label,type,required,options});
export const FORM_SCHEMAS: Record<string,FormSchema> = {
 'employee-create':{formId:'employee-create',sections:[
  {title:'Basic Information',fields:[f('employee_id','Employee ID','text',true),f('full_name_en','Full Name in English','text',true),f('full_name_bn','Full Name in Bangla'),f('photo','Original Employee Photo','image',true),f('date_of_birth','Date of Birth','date'),f('blood_group','Blood Group','select')]},
  {title:'Contact Information',fields:[f('phone','Primary Phone','phone',true),f('email','Email','email'),f('present_address','Present Address','multiline'),f('emergency_phone','Emergency Contact Phone','phone')]},
  {title:'Employment',fields:[f('department_id','Department','select',true),f('designation_id','Designation','select',true),f('joining_date','Joining Date','date',true),f('role','Employee Role','select'),f('status','Employment Status','select',true)]},
  {title:'Identification & Account',fields:[f('nid_number','NID Number'),f('nid_front','NID Front','file'),f('create_login','Create Application Login','select'),f('temporary_password','Temporary Password')]},
 ]},
 'employee-id-card-issue':{formId:'employee-id-card-issue',sections:[{title:'Card Identity',fields:[f('employee_id','Employee','select',true),f('issue_date','Issue Date','date',true),f('expiry_date','Expiry Date','date',true),f('card_status','Card Status','select',true),f('qr_enabled','QR Verification Enabled','select',true)]}]},
 'attendance-check-in':{formId:'attendance-check-in',sections:[{title:'Verified Check-In',fields:[f('location','Current GPS Location','location',true),f('accuracy','GPS Accuracy','number',true),f('work_location_id','Detected Work Location','select'),f('purpose','Field Attendance Purpose','multiline'),f('idempotency_key','Request Reference','text',true)]}]},
 'attendance-check-out':{formId:'attendance-check-out',sections:[{title:'Verified Check-Out',fields:[f('attendance_session_id','Active Attendance Session','select',true),f('location','Current GPS Location','location',true),f('work_summary','Work Summary','multiline'),f('idempotency_key','Request Reference','text',true)]}]},
 'message-compose':{formId:'message-compose',sections:[{title:'Message',fields:[f('recipient_type','Recipient Type','select',true),f('recipients','Recipients','select',true),f('subject','Subject','text',true),f('message','Message','multiline',true),f('priority','Priority','select'),f('attachment','Attachment','file'),f('send_push','Send Push Notification','select')]}]},
 'message-group-create':{formId:'message-group-create',sections:[{title:'Group',fields:[f('group_name','Group Name','text',true),f('group_type','Group Type','select',true),f('members','Members','select',true),f('administrators','Group Administrators','select'),f('description','Description','multiline')]}]},
 'push-notification-create':{formId:'push-notification-create',sections:[{title:'Campaign',fields:[f('campaign_name','Campaign Name','text',true),f('title','Notification Title','text',true),f('body','Notification Body','multiline',true),f('audience_type','Audience Type','select',true),f('deep_link','Deep-Link Destination'),f('delivery_mode','Delivery Mode','select',true),f('scheduled_at','Scheduled Date and Time','text')]}]},
 'customer-create':{formId:'customer-create',sections:[{title:'Customer',fields:[f('customer_type','Customer Type','select',true),f('customer_id','Customer ID','text',true),f('company_name','Company Name','text',true),f('contact_person','Contact Person'),f('phone','Phone','phone',true),f('service_address','Service Address','multiline'),f('opening_balance','Opening Balance','currency')]}]},
 'task-create':{formId:'task-create',sections:[{title:'Task',fields:[f('title','Task Title','text',true),f('description','Task Description','multiline',true),f('department_id','Department','select'),f('assigned_employee_id','Assigned Employee','select',true),f('priority','Priority','select',true),f('due_date','Due Date','date',true),f('related_customer_id','Related Customer','select')]}]},
 'engineer-create':{formId:'engineer-create',sections:[{title:'Engineer Profile',fields:[f('employee_id','Employee','select',true),f('engineer_code','Engineer Code','text',true),f('specialization','Specialization','multiline',true),f('service_areas','Service Areas','multiline'),f('maximum_daily_jobs','Maximum Daily Jobs','number')]}]},
 'engineer-schedule-create':{formId:'engineer-schedule-create',sections:[{title:'Schedule',fields:[f('engineer_id','Engineer','select',true),f('schedule_type','Schedule Type','select',true),f('customer_id','Customer','select'),f('date','Date','date',true),f('start_time','Start Time','time',true),f('location','Location','location',true),f('instructions','Instructions','multiline')]}]},
 'service-ticket-create':{formId:'service-ticket-create',sections:[{title:'Service Request',fields:[f('ticket_source','Ticket Source','select',true),f('customer_id','Customer','select',true),f('machine_id','Machine','select',true),f('serial_number','Serial Number'),f('problem_description','Problem Description','multiline',true),f('priority','Priority','select',true),f('photos','Photos','image')]}]},
 'warranty-create':{formId:'warranty-create',sections:[{title:'Warranty',fields:[f('customer_id','Customer','select',true),f('machine_id','Machine','select',true),f('serial_number','Serial Number','text',true),f('invoice_id','Invoice','select'),f('warranty_start','Warranty Start','date',true),f('warranty_end','Warranty End','date',true),f('covered_parts','Covered Parts','multiline')]}]},
 'product-create':{formId:'product-create',sections:[{title:'Product',fields:[f('name','Product Name','text',true),f('category_id','Category','select',true),f('sku','SKU','text',true),f('unit','Unit','select',true),f('purchase_price','Purchase Price','currency'),f('selling_price','Selling Price','currency'),f('opening_stock','Opening Stock','number'),f('image','Product Image','image')]}]},
 'stock-in-create':{formId:'stock-in-create',sections:[{title:'Stock In',fields:[f('source_type','Source Type','select',true),f('warehouse_id','Warehouse','select',true),f('product_id','Product','select',true),f('quantity','Quantity','number',true),f('unit_cost','Unit Cost','currency'),f('received_date','Received Date','date',true)]}]},
 'stock-out-create':{formId:'stock-out-create',sections:[{title:'Stock Out',fields:[f('purpose','Purpose','select',true),f('warehouse_id','Warehouse','select',true),f('product_id','Product','select',true),f('available_stock','Available Stock','number'),f('quantity','Quantity','number',true),f('service_ticket_id','Service Ticket','select')]}]},
 'supplier-create':{formId:'supplier-create',sections:[{title:'Supplier',fields:[f('supplier_code','Supplier Code','text',true),f('name','Supplier Name','text',true),f('country','Country','text',true),f('phone','Phone','phone'),f('whatsapp','WhatsApp','phone'),f('currency','Currency','select'),f('business_type','Business Type','select')]}]},
 'purchase-order-create':{formId:'purchase-order-create',sections:[{title:'Purchase Order',fields:[f('supplier_id','Supplier','select',true),f('purchase_type','Purchase Type','select',true),f('po_date','PO Date','date',true),f('currency','Currency','select',true),f('exchange_rate','Exchange Rate','number'),f('items','Products and Quantities','multiline',true)]}]},
 'lc-record-create':{formId:'lc-record-create',sections:[{title:'LC Record',fields:[f('supplier_id','Supplier','select',true),f('bank_id','Bank','select',true),f('lc_number','LC Number','text',true),f('opening_date','LC Opening Date','date',true),f('currency','Currency','select',true),f('lc_value','LC Value','currency',true),f('expiry_date','Expiry Date','date')]}]},
 'shipment-create':{formId:'shipment-create',sections:[{title:'Shipment',fields:[f('shipment_number','Shipment Number','text',true),f('supplier_id','Supplier','select',true),f('shipment_mode','Shipment Mode','select',true),f('bl_awb_number','BL/AWB Number'),f('etd','ETD','date'),f('eta','ETA','date',true),f('documents','Documents','file')]}]},
 'payment-create':{formId:'payment-create',sections:[{title:'Payment',fields:[f('customer_id','Customer','select',true),f('invoice_id','Invoice','select',true),f('payment_date','Payment Date','date',true),f('payment_method','Payment Method','select',true),f('account_id','Cash/Bank Account','select',true),f('amount','Amount','currency',true),f('idempotency_key','Request Reference','text',true)]}]},
 'expense-create':{formId:'expense-create',sections:[{title:'Expense',fields:[f('expense_date','Expense Date','date',true),f('category_id','Category','select',true),f('payee','Payee','text',true),f('account_id','Cash/Bank Account','select',true),f('amount','Amount','currency',true),f('document','Document','file')]}]},
 'agreement-create':{formId:'agreement-create',sections:[{title:'Agreement',fields:[f('customer_id','Customer','select',true),f('nid','NID','text',true),f('machine_id','Machine','select',true),f('cash_price','Cash Price','currency',true),f('down_payment','Down Payment','currency',true),f('emi_months','EMI Months','number',true),f('first_due_date','First Due Date','date',true),f('customer_signature','Customer Signature','signature',true)]}]},
 'document-create':{formId:'document-create',sections:[{title:'Document',fields:[f('category','Document Category','select',true),f('title','Document Title','text',true),f('entity_type','Related Entity Type','select',true),f('entity_id','Related Record','select',true),f('file','File Upload','file',true),f('visibility','Visibility','select',true)]}]},
 'user-create':{formId:'user-create',sections:[{title:'User Account',fields:[f('user_type','User Type','select',true),f('name','Name','text',true),f('login_id','Login ID','text',true),f('role_id','Role','select',true),f('temporary_password','Temporary Password','text',true),f('force_password_change','Force Password Change','select',true)]}]},
};
export function getFormSchema(formId:string):FormSchema {
 const schema=FORM_SCHEMAS[formId];
 if(!schema) throw new Error(`FORM_SCHEMA_CONFIGURATION_ERROR: Missing explicit schema for "${formId}".`);
 return schema;
}
