import React,{useState} from 'react';
import {ActivityIndicator,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {router,useLocalSearchParams} from 'expo-router';
import {Screen} from '@/src/components/ui/Screen';
import {MODULE_MAP} from '@/src/core/moduleRegistry';
import {contractFor} from '@/src/services/moduleApi';
import {apiPost} from '@/src/services/erpApi';
import {colors,radius,spacing,typography} from '@/src/theme/tokens';
export default function NewRecord(){const{key}=useLocalSearchParams<{key:string}>();const module=MODULE_MAP[key??''];const contract=contractFor(key??'');const[values,setValues]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');if(!module||!contract.create)return <View style={s.center}><Text>This form is not available.</Text></View>;const moduleDef=module;const createEndpoint=contract.create;async function save(){for(const f of moduleDef.fields)if(f.required&&!String(values[f.key]??'').trim()){setMessage(`${f.label} is required.`);return}const payload:Record<string,unknown>={};for(const f of moduleDef.fields){const raw=String(values[f.key]??'').trim();if(raw)payload[f.key]=['number','currency'].includes(f.type)?Number(raw):raw}try{setBusy(true);setMessage('');await apiPost(createEndpoint,payload);router.replace({pathname:'/module/[key]',params:{key:moduleDef.key}})}catch(e){setMessage(e instanceof Error?e.message:'Could not save record.')}finally{setBusy(false)}}return <Screen keyboardShouldPersistTaps="handled"><View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={21} color={colors.primary}/></Pressable><View><Text style={s.eyebrow}>SECURE CPANEL FORM</Text><Text style={s.title}>New {moduleDef.title}</Text></View></View><View style={s.note}><Ionicons name="shield-checkmark-outline" size={18} color={colors.primary}/><Text style={s.noteText}>Fields, role permissions and validation are checked again by the cPanel ERP server.</Text></View>{moduleDef.fields.map(field=><View key={field.key} style={s.group}><Text style={s.label}>{field.label}{field.required?' *':''}</Text><TextInput style={[s.input,field.type==='notes'&&s.multiline]} value={values[field.key]??''} onChangeText={value=>setValues(current=>({...current,[field.key]:value}))} placeholder={field.placeholder??field.label} placeholderTextColor={colors.mutedForeground} keyboardType={['number','currency'].includes(field.type)?'decimal-pad':field.type==='phone'?'phone-pad':field.type==='email'?'email-address':'default'} multiline={field.type==='notes'} textAlignVertical={field.type==='notes'?'top':'center'}/></View>)}{message?<Text style={s.error}>{message}</Text>:null}<Pressable style={[s.save,busy&&{opacity:.6}]} onPress={save} disabled={busy}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.saveText}>Save to cPanel ERP</Text>}</Pressable></Screen>}
const s=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center'},header:{minHeight:70,flexDirection:'row',alignItems:'center',gap:spacing.md},back:{width:40,height:40,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card,alignItems:'center',justifyContent:'center'},eyebrow:{fontFamily:typography.bold,fontSize:8,color:colors.accent,letterSpacing:1},title:{fontFamily:typography.bold,fontSize:19,color:colors.text},note:{backgroundColor:colors.navyLight,borderRadius:radius.md,padding:spacing.md,flexDirection:'row',gap:9,marginBottom:spacing.md},noteText:{flex:1,fontFamily:typography.regular,color:colors.secondary,fontSize:10,lineHeight:16},group:{gap:6,marginBottom:spacing.md},label:{fontFamily:typography.semibold,color:colors.secondary,fontSize:11},input:{minHeight:52,backgroundColor:colors.card,borderColor:colors.border,borderWidth:1,borderRadius:radius.md,paddingHorizontal:13,paddingVertical:10,color:colors.text,fontFamily:typography.regular},multiline:{minHeight:110},save:{height:54,borderRadius:radius.md,alignItems:'center',justifyContent:'center',backgroundColor:colors.primary,marginBottom:spacing.xxl},saveText:{color:'#fff',fontFamily:typography.bold,fontSize:15},error:{color:colors.destructive,fontFamily:typography.semibold,marginBottom:spacing.md}})
