apply plugin: ['com','android','application'].join('.')

android {
    namespace 'com.colorjetbd.managementsuite'
    compileSdkVersion 35
    defaultConfig {
        applicationId 'com.colorjetbd.managementsuite'
        minSdkVersion 24
        targetSdkVersion 35
        versionCode 1
        versionName '1.0.0'
    }
}
