import { useCallback,useEffect,useState } from 'react';
import { Ionicons } from '@expo/vector-icons';
import { ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from 'react-native';
import { router,useLocalSearchParams } from 'expo-router';
import { apiGet } from '../../lib/erp-api';
import { moduleByKey } from '../../constants/modules';
import { colors,radius,spacing,statusColor } from '../../lib/theme';
function rowsOf(x:any):any[]{if(Array.isArray(x))return x;if(Array.isArray(x?.items))return x.items;if(Array.isArray(x?.rows))return x.rows;if(Array.isArray(x?.data))return x.data;return []}
export default function ModuleScreen(){const {type}=useLocalSearchParams<{type:string}>();const config=moduleByKey[String(type)];const [rows,setRows]=useState<any[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState('');const load=useCallback(async()=>{if(!config)return;setBusy(true);setError('');try{setRows(rowsOf(await apiGet<any>(config.listPath)))}catch(e){setError(e instanceof Error?e.message:'Load failed')}finally{setBusy(false)}},[config]);useEffect(()=>{void load()},[load]);if(!config)return <SafeAreaView style={s.page}><Text>Unknown module.</Text></SafeAreaView>;return <SafeAreaView style={s.page}><View style={s.header}><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={23} color="#fff"/></Pressable><View style={{flex:1}}><Text style={s.title}>{config.title}</Text><Text style={s.sub}>{config.subtitle}</Text></View>{config.createPath?<Pressable style={s.add} onPress={()=>router.push(`/new/${config.key}`)}><Ionicons name="add" size={24} color="#fff"/></Pressable>:null}</View><ScrollView contentContainerStyle={s.content}>{busy?<ActivityIndicator color={colors.primary}/>:null}{error?<Pressable style={s.error} onPress={()=>void load()}><Text style={s.errorText}>{error} · Tap to retry</Text></Pressable>:null}{!busy&&!error&&!rows.length?<Text style={s.empty}>No records returned by the cPanel API.</Text>:null}{rows.map((row,i)=><View style={s.card} key={String(row.id??i)}><Text style={s.primary}>{config.primaryKeys.map(k=>row[k]).find(Boolean)??`${config.title} #${i+1}`}</Text>{config.secondaryKeys.map(k=>row[k]!==undefined&&row[k]!==null?<Text key={k} style={s.secondary}>{k.replace(/_/g,' ')}: {String(row[k])}</Text>:null)}{config.statusKeys?.map(k=>row[k]?<Text key={k} style={[s.status,{color:statusColor(String(row[k]))}]}>{String(row[k])}</Text>:null)}</View>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},header:{backgroundColor:colors.navy,padding:16,flexDirection:'row',alignItems:'center',gap:12},title:{color:'#fff',fontSize:18,fontWeight:'900'},sub:{color:'#BFD7EE',fontSize:11,marginTop:2},add:{width:40,height:40,borderRadius:12,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},content:{padding:spacing.lg},error:{padding:14,borderRadius:radius.md,backgroundColor:colors.softRed},errorText:{color:colors.red,fontWeight:'800'},empty:{textAlign:'center',color:colors.muted,marginTop:30},card:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:14,marginBottom:9},primary:{fontSize:15,fontWeight:'900',color:colors.text},secondary:{fontSize:12,color:colors.secondary,marginTop:5},status:{fontSize:11,fontWeight:'900',marginTop:7,textTransform:'uppercase'}})
