import { useEffect,useState } from 'react';
import * as Location from 'expo-location';
import { SafeAreaView,StyleSheet,Text } from 'react-native';
import { apiGet,apiPost } from '../lib/erp-api';
import { ensureLocationPermissions,startBackgroundRoute,stopBackgroundRoute } from '../lib/background-location';
import { Button,Card } from '../components/UI';
import { colors } from '../lib/theme';
export default function Attendance(){const [status,setStatus]=useState('Loading…'),[busy,setBusy]=useState(false);useEffect(()=>{void apiGet<any>('operations/attendance/today').then(x=>setStatus(x?.status??'Not checked in')).catch(e=>setStatus(e.message))},[]);async function checkIn(){setBusy(true);try{await ensureLocationPermissions();const p=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});const r=await apiPost<any>('operations/attendance/check-in',{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_m:p.coords.accuracy,is_mock:p.mocked?1:0});const id=String(r?.session_uuid??r?.route_session_uuid??'');if(id)await startBackgroundRoute(id);setStatus('Checked in')}catch(e){setStatus(e instanceof Error?e.message:'Check-in failed')}finally{setBusy(false)}}async function checkOut(){setBusy(true);try{const p=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});await apiPost('operations/attendance/check-out',{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy_m:p.coords.accuracy,is_mock:p.mocked?1:0});await stopBackgroundRoute();setStatus('Checked out')}catch(e){setStatus(e instanceof Error?e.message:'Check-out failed')}finally{setBusy(false)}}return <SafeAreaView style={s.page}><Card><Text style={s.title}>Attendance Status</Text><Text style={s.status}>{status}</Text><Button title="GPS Check In" onPress={()=>void checkIn()} loading={busy}/><Button title="GPS Check Out" variant="outline" onPress={()=>void checkOut()} loading={busy}/></Card><Text style={s.note}>Background route recording runs only during an active duty session and shows an Android foreground notification.</Text></SafeAreaView>}
const s=StyleSheet.create({page:{flex:1,padding:18,backgroundColor:colors.background},title:{fontSize:20,fontWeight:'900',color:colors.text},status:{fontSize:15,color:colors.secondary,marginVertical:16},note:{fontSize:12,lineHeight:18,color:colors.muted,marginTop:14}})
