import { useEffect,useMemo,useState } from 'react';
import { Ionicons } from '@expo/vector-icons';
import { Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from 'react-native';
import { router } from 'expo-router';
import { ApiUser,getSession,logout } from '../lib/erp-api';
import { moduleGroups,modules } from '../constants/modules';
import { colors,radius,spacing } from '../lib/theme';
export default function Home(){const [user,setUser]=useState<ApiUser|null>(null);useEffect(()=>{void getSession().then(s=>setUser(s?.user??null))},[]);const role=String(user?.role??'').toUpperCase();const visible=useMemo(()=>modules.filter(m=>!m.roles||m.roles.includes(role)),[role]);return <SafeAreaView style={s.page}><View style={s.header}><View><Text style={s.eye}>COLORJET MANAGEMENT SUITE</Text><Text style={s.title}>Authorized ERP Modules</Text><Text style={s.role}>{user?.full_name||user?.name||'User'} · {role||'AUTHORIZED'}</Text></View><Pressable onPress={async()=>{await logout();router.replace('/')}}><Ionicons name="log-out-outline" size={26} color="#fff"/></Pressable></View><ScrollView contentContainerStyle={s.content}><Pressable style={s.attendance} onPress={()=>router.push('/attendance')}><Ionicons name="location-outline" size={26} color="#fff"/><View><Text style={s.attTitle}>GPS Attendance & Duty Route</Text><Text style={s.attSub}>Check in/out with location evidence</Text></View></Pressable>{moduleGroups.map(group=>{const list=visible.filter(m=>m.group===group);if(!list.length)return null;return <View key={group}><Text style={s.group}>{group}</Text>{list.map(m=><Pressable key={m.key} style={s.item} onPress={()=>router.push(`/module/${m.key}`)}><View style={s.icon}><Ionicons name={m.icon} size={21} color={colors.primary}/></View><View style={{flex:1}}><Text style={s.itemTitle}>{m.title}</Text><Text style={s.itemSub}>{m.subtitle}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.muted}/></Pressable>)}</View>})}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},header:{backgroundColor:colors.navy,padding:spacing.lg,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eye:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1},title:{color:'#fff',fontSize:21,fontWeight:'900',marginTop:3},role:{color:'#BFD7EE',fontSize:11,marginTop:4},content:{padding:spacing.lg,paddingBottom:40},attendance:{backgroundColor:colors.primary,borderRadius:radius.lg,padding:spacing.lg,flexDirection:'row',gap:12,alignItems:'center'},attTitle:{color:'#fff',fontWeight:'900'},attSub:{color:'#EAF7FF',fontSize:12,marginTop:3},group:{color:colors.navy,fontSize:15,fontWeight:'900',marginTop:22,marginBottom:8},item:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:12,flexDirection:'row',alignItems:'center',gap:12,marginBottom:8},icon:{width:42,height:42,borderRadius:12,backgroundColor:colors.softBlue,alignItems:'center',justifyContent:'center'},itemTitle:{fontSize:15,fontWeight:'800',color:colors.text},itemSub:{fontSize:11,color:colors.secondary,marginTop:3}})
