import { useEffect,useState } from 'react';
import { Image,KeyboardAvoidingView,Platform,Pressable,StyleSheet,Text,TextInput,View } from 'react-native';
import { router } from 'expo-router';
import { login,getSession } from '../lib/erp-api';
import { getApiBaseUrl } from '../lib/runtime-config';
import { Button,Card } from '../components/UI';
import { colors } from '../lib/theme';
export default function Login(){const [user,setUser]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(true),[error,setError]=useState('');useEffect(()=>{void (async()=>{if(!await getApiBaseUrl()){router.replace('/setup');return}if(await getSession()){router.replace('/home');return}setBusy(false)})()},[]);async function submit(){setBusy(true);setError('');try{await login(user.trim(),password);router.replace('/home')}catch(e){setError(e instanceof Error?e.message:'Login failed')}finally{setBusy(false)}}return <KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={s.page}><View style={s.brand}><Image source={require('../assets/images/colorjet-original-icon.png')} resizeMode="contain" style={s.logo}/><Text style={s.title}>Management Suite</Text><Text style={s.subtitle}>Quality • Commitment • Service</Text></View><Card><Text style={s.label}>Email / Phone / Employee ID</Text><TextInput autoCapitalize="none" value={user} onChangeText={setUser} style={s.input}/><Text style={s.label}>Password</Text><TextInput secureTextEntry value={password} onChangeText={setPassword} style={s.input}/><Button title="Secure Sign In" onPress={submit} loading={busy}/>{error?<Text style={s.error}>{error}</Text>:null}<Pressable onPress={()=>router.push('/setup')}><Text style={s.setup}>Server Setup</Text></Pressable></Card></KeyboardAvoidingView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.background,justifyContent:'center',padding:22},brand:{alignItems:'center',marginBottom:24},logo:{width:180,height:72},title:{fontSize:25,fontWeight:'900',color:colors.navy,marginTop:8},subtitle:{fontSize:13,color:colors.muted},label:{fontSize:12,fontWeight:'800',color:colors.text,marginTop:6},input:{borderWidth:1,borderColor:colors.border,borderRadius:10,backgroundColor:'#fff',padding:12,marginTop:6,marginBottom:8},error:{color:colors.red,marginTop:10},setup:{textAlign:'center',color:colors.primary,fontWeight:'900',marginTop:14}})
